### ISSUE TITLE
Nothing shows up after you click the book in the main page

### ISSUE THREAD

**Issue by ethanhanderson** [bo-ok/bo-ok.github.io#1]
When you go to the main page and click on the book, you are redirected to a blank page... Has nothing been put in there yet? If not, could I work on whatever needs to be in there?

**Comment by bo-ok** [comment]
Yeah, there's nothing there yet. Its called "/o-o.html"
If you wanna edit it or something go ahead.
idk some type of WIP

**Comment by ethanhanderson** [comment]
Ah, okay cool.
